import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "react, app, mobile, website"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="root-layout">
          {children}
        </div>
      </body>
    </html>
  );
}